services:
  hardhat-node:
    build: .
    ports:
      - "8545:8545"
    environment:
      - NODE_ENV=development
    volumes:
      - ./contracts:/app/contracts
      - ./scripts:/app/scripts
      - ./artifacts:/app/artifacts
      - ./cache:/app/cache
      - hardhat-data:/app/hardhat-data
      - ./blockchain-state.json:/app/blockchain-state.json  # Добавляем файл состояния
    restart: unless-stopped
    networks:
      - qrb-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H", "Content-Type: application/json", "--data", "{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  qrb-network:
    external: true

volumes:
  hardhat-data: